### ISSUE TITLE
17.0.0 firmware support needed

### ISSUE THREAD

**Issue by gradius3** [rsn8887/Hurrican#2]
game crashes/hangs after completing first level on cfw 17.0.0

**Comment by rsn8887** [comment]
I re-compiled using latest SDK, please test this version:
https://files.coolatoms.org/Hurrican_1.02_switch_test.zip

**Comment by gradius3** [comment]
sadly the game doesn't run at all now. It says that an error occured and the game couldn't be started. Exits out afterwards.

**Comment by rsn8887** [comment]
Something must have broken in the SDK then, since the game source code hasn’t changed. I will have to investigate this further.

**Comment by rsn8887** [comment]
I just made a new release v1.03 here on Patreon. It should fix your problems.

**Comment by rsn8887** [comment]
Fixed in release 1.03

**Comment by gradius3** [comment]
Thanks for your efforts and fast update. Seems to be working fine at first. But pressing X ingame (tutorial as well) to start the controllable laser makes the game crash again.

**Comment by rsn8887** [comment]
v1.03 still had problems. 

Did you try v1.04? I tried the controllable laser in v1.04 and it worked for me.

**Comment by gradius3** [comment]
Working fine now. THANK YOU!
